site_name: Massive Text Embedding Benchmark
docs_dir: "docs/"
repo_url: https://github.com/embeddings-benchmark/mteb
watch: [mteb/, docs/]
edit_uri: "blob/main/docs/"
theme:
  favicon: images/logos/mteb_logo/dots-icon.png
  logo: images/logos/mteb_logo/dots-icon.png
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
    - content.code.annotation
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - toc.follow
  palette:
    # System preference (auto)
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      toc_depth: 3
  - footnotes
  - attr_list
  - md_in_html
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Get Started:
      - index.md
      - installation.md
      - whats_new.md
      - Usage:
        - Get Started: get_started/usage/get_started.md
        - Define the Model: get_started/usage/defining_the_model.md
        - Select Benchmarks: get_started/usage/selecting_tasks.md
        - Run the Evaluation: get_started/usage/running_the_evaluation.md
        - Load Results: get_started/usage/loading_results.md
        - Command Line: get_started/usage/cli.md
        - Run the Leaderboard: get_started/usage/leaderboard.md
      - Advanced Usage:
        - Two stage reranking: get_started/advanced_usage/two_stage_reranking.md
        - Cache embeddings: get_started/advanced_usage/cache_embeddings.md
        - Retrieval backend: get_started/advanced_usage/retrieval_backend.md
        - vLLM Wrapper: get_started/advanced_usage/vllm_wrapper.md
  - Contributing:
      - Adding a Model: contributing/adding_a_model.md
      - Adding a Task: contributing/adding_a_dataset.md
      - Adding a Benchmark: contributing/adding_a_benchmark.md
      - CONTRIBUTING.md
  - Overview:
      - overview/index.md
      - Benchmarks:
        - Available Benchmarks: overview/available_benchmarks.md
      - Models:
        - Text: overview/available_models/text.md
        - Image: overview/available_models/image.md
        - Image Text: overview/available_models/image_text.md
        - Audio: overview/available_models/audio.md
        - Audio Text: overview/available_models/audio_text.md
        - Multimodal: overview/available_models/multimodal.md
      - Tasks:
        - overview/available_tasks/retrieval.md
        - overview/available_tasks/audiopairclassification.md
        - overview/available_tasks/summarization.md
        - overview/available_tasks/documentunderstanding.md
        - overview/available_tasks/compositionality.md
        - overview/available_tasks/multilabelclassification.md
        - overview/available_tasks/reranking.md
        - overview/available_tasks/any2anymultilingualretrieval.md
        - overview/available_tasks/pairclassification.md
        - overview/available_tasks/bitextmining.md
        - overview/available_tasks/audiomultilabelclassification.md
        - overview/available_tasks/visualsts(eng).md
        - overview/available_tasks/clustering.md
        - overview/available_tasks/any2anyretrieval.md
        - overview/available_tasks/regression.md
        - overview/available_tasks/classification.md
        - overview/available_tasks/audiozeroshotclassification.md
        - overview/available_tasks/visualsts(multi).md
        - overview/available_tasks/visioncentricqa.md
        - overview/available_tasks/sts.md
        - overview/available_tasks/audioclassification.md
        - overview/available_tasks/zeroshotclassification.md
        - overview/available_tasks/imageclustering.md
        - overview/available_tasks/audioclustering.md
        - overview/available_tasks/instructionretrieval.md
        - overview/available_tasks/audioreranking.md
        - overview/available_tasks/instructionreranking.md
        - overview/available_tasks/imageclassification.md
  - API:
      - Overview: api/index.md
      - Evaluation: api/evaluation.md
      - Benchmark: api/benchmark.md
      - Task: api/task.md
      - Model: api/model.md
      - Results: api/results.md
      - Additional Types: api/types.md
  - Leaderboard: https://huggingface.co/spaces/mteb/leaderboard

copyright: This site made available under a Creative Commons Attribution 4.0 license

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [mteb]
          type: python
          root_package: mteb
          docstring_style: google
          options:
            heading_level: 3
            show_source: true
            show_root_heading: true

extra_javascript:
  - javascripts/extra.js
extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/embeddings-benchmark/mteb
