name: 🗃 New dataset
description: Create a request for a new dataset to be added to MTEB
title: "Add dataset: {dataset_name}"
labels: ["new dataset"]
body:
  - type: input
    attributes:
      label: dataset link on Hugging dataset
      description: Please provide a link to the dataset, ideally to Hugging Face.
    validations:
      required: true
  - type: input
    attributes:
      label: Arxiv link
      description: If the dataset is based on a paper, please provide a link to the paper on Arxiv or another academic repository.
  - type: textarea
    attributes:
      label: Description of the dataset
      description: Please provide a clear and concise description of the dataset you would like to see added.
