name: Datasets available on HuggingFace - PR

on:
  pull_request:
    paths:
      - "mteb/tasks/**.py"

jobs:
  run-pr-datasets-loading-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
          make install-for-tests

    - name: Run dataset loading tests
      run: |
        make dataset-load-test-pr BASE_BRANCH=${{ github.event.pull_request.base.ref }}
