name: Datasets available on HuggingFace
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "mteb/tasks/**.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  dataset-loading-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Install uv
      uses: astral-sh/setup-uv@v8.2.0
      with:
        enable-cache: true
        version: "0.10.12"
        python-version: '3.10'

    - name: Install dependencies
      timeout-minutes: 5
      id: sync
      continue-on-error: true
      run: |
        uv sync --group test --frozen --verbose

    - name: Create venv manually and sync (fallback)
      if: steps.sync.outcome == 'failure'
      timeout-minutes: 10
      run: |
        rm -rf .venv
        $(uv python find) -m venv .venv
        uv sync --group test --frozen --verbose

    - name: Run dataset loading tests
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          make dataset-load-test-pr BASE_BRANCH=${{ github.event.pull_request.base.ref }}
        else
          make dataset-load-test
        fi
