name: Model Loading

on:
  pull_request:
    paths:
      - "mteb/models/**.py"
      - "pyproject.toml"
      - "uv.lock"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  extract-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          python-version: "3.10"

      - name: Install dependencies and run tests
        run: |
          make model-load-test BASE_BRANCH=${{ github.event.pull_request.base.ref }}
