name: Typechecking

on:
  push:
    branches: [main]
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          python-version: "3.10"

      - name: Install dependencies
        run: |
          make install-for-tests

      - name: Run typecheck
        run: |
          make typecheck
