name: Typechecking

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Install uv
        uses: astral-sh/setup-uv@v8
        with:
          enable-cache: true
          python-version: "3.10"

      - name: Install dependencies
        run: |
          make install-for-tests

      - name: Build and Deploy
        run: |
          make typecheck
